parameters:
#    annuaire.example.class: Annuaire\AnnuaireBundle\Example

services:
#    annuaire.example:
#        class: %annuaire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
