<?php

namespace Annuaire\AnnuaireBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
	 public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.nom like :chaine' )
            ->orWhere('u.prenom like :chaine')
            ->orWhere('u.numEmp like :chaine')
            ->orWhere('u.fonction like :chaine')
            ->orWhere('u.nomService like :chaine')
            ->orWhere('u.departement like :chaine') 
            ->orWhere('u.localisation like :chaine')   
            ->orWhere('u.numBureau like :chaine')  
            ->groupBy('u.prenom')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);

        


        return $qb->getQuery()->getResult();
      
    }
    
}
