<?php

namespace Annuaire\AnnuaireBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RessourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourcesRepository extends EntityRepository
{
	 public function recherche($chaine)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.ressource like :chaine' )
            ->orWhere('u.type like :chaine')
            ->orWhere('u.marque like :chaine')
            ->groupBy('u.ressource')
            ->orderBy('u.id')
            ->setParameter('chaine', $chaine);
        
        return $qb->getQuery()->getResult();
      
    }

}
