<?php

namespace Proxies\__CG__\Annuaire\AnnuaireBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Employee extends \Annuaire\AnnuaireBundle\Entity\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCivilite($civilite)
    {
        $this->__load();
        return parent::setCivilite($civilite);
    }

    public function getCivilite()
    {
        $this->__load();
        return parent::getCivilite();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function setDateNaiss($dateNaiss)
    {
        $this->__load();
        return parent::setDateNaiss($dateNaiss);
    }

    public function getDateNaiss()
    {
        $this->__load();
        return parent::getDateNaiss();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setComplementAdr($complementAdr)
    {
        $this->__load();
        return parent::setComplementAdr($complementAdr);
    }

    public function getComplementAdr()
    {
        $this->__load();
        return parent::getComplementAdr();
    }

    public function setVille($ville)
    {
        $this->__load();
        return parent::setVille($ville);
    }

    public function getVille()
    {
        $this->__load();
        return parent::getVille();
    }

    public function setNumTel($numTel)
    {
        $this->__load();
        return parent::setNumTel($numTel);
    }

    public function getNumTel()
    {
        $this->__load();
        return parent::getNumTel();
    }

    public function setNumPro($numPro)
    {
        $this->__load();
        return parent::setNumPro($numPro);
    }

    public function getNumPro()
    {
        $this->__load();
        return parent::getNumPro();
    }

    public function setNumBureau($numBureau)
    {
        $this->__load();
        return parent::setNumBureau($numBureau);
    }

    public function getNumBureau()
    {
        $this->__load();
        return parent::getNumBureau();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setNumEmp($numEmp)
    {
        $this->__load();
        return parent::setNumEmp($numEmp);
    }

    public function getNumEmp()
    {
        $this->__load();
        return parent::getNumEmp();
    }

    public function setFontion($fontion)
    {
        $this->__load();
        return parent::setFontion($fontion);
    }

    public function getFontion()
    {
        $this->__load();
        return parent::getFontion();
    }

    public function setDepartement($departement)
    {
        $this->__load();
        return parent::setDepartement($departement);
    }

    public function getDepartement()
    {
        $this->__load();
        return parent::getDepartement();
    }

    public function setLocalisation($localisation)
    {
        $this->__load();
        return parent::setLocalisation($localisation);
    }

    public function getLocalisation()
    {
        $this->__load();
        return parent::getLocalisation();
    }

    public function setNomService($nomService)
    {
        $this->__load();
        return parent::setNomService($nomService);
    }

    public function getNomService()
    {
        $this->__load();
        return parent::getNomService();
    }

    public function setFonction($fonction)
    {
        $this->__load();
        return parent::setFonction($fonction);
    }

    public function getFonction()
    {
        $this->__load();
        return parent::getFonction();
    }

    public function setUtilisateur(\Utilisateurs\UtilisateurBundle\Entity\Utilisateurs $utilisateur = NULL)
    {
        $this->__load();
        return parent::setUtilisateur($utilisateur);
    }

    public function getUtilisateur()
    {
        $this->__load();
        return parent::getUtilisateur();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'civilite', 'nom', 'prenom', 'dateNaiss', 'adresse', 'complementAdr', 'ville', 'numTel', 'numPro', 'numBureau', 'email', 'numEmp', 'fonction', 'departement', 'localisation', 'nomService', 'utilisateur');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}